version: '2.1'

services:
  app:
    container_name: carpeta-ciudadana
    image: carpeta-ciudadana:1.0.0
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:12.2
    command: postgres -c 'max_connections=10000'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=Prueba123*
    volumes:
    - ./data:/data/db