version: '2.1'

services:
  app:
    container_name: carpeta-ciudadana
    image: ronaldkm98/carpeta-ciudadana:1.0.0
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: ronaldkm98/postgresql:1.0.1
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=Prueba123*
      - POSTGRES_USER=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=postgres
    volumes:
      - ${WEBAPP_STORAGE_HOME}/postgres_data:/var/lib/postgresql
    ports:
      - "5432:5432"
    command: postgres
